const problemsDatabase = {
    "python": [
        {
            "title": "Two Sum (O(N) Time)",
            "difficulty": "Easy",
            "timeLimit": "10m",
            "desc": "The LLM generated a brute-force O(N^2) solution using nested loops. Optimize it to O(N) using a hash map.",
            "example": "Input: nums = [2,7,11,15], target = 9\nOutput: [0,1]",
            "hint1": "You can solve this in one pass.",
            "hint2": "Store the complement of each number in a dictionary as you iterate.",
            "code": "class Solution:\n    def twoSum(self, nums, target):\n        for i in range(len(nums)):\n            for j in range(i+1, len(nums)):\n                if nums[i] + nums[j] == target:\n                    return [i, j]\n        return []",
            "fail_regex": "for j in range",
            "fail_msg": "Your solution is still O(N^2) because of the nested loop. Use a dictionary.",
            "pass_regex": "\\{.*\\}|dict\\(|in ",
            "pass_msg": "Great! You used a hash map to achieve O(N) time complexity."
        },
        {
            "title": "Detect Cycle in Linked List (O(1) Space)",
            "difficulty": "Hard",
            "timeLimit": "15m",
            "desc": "The LLM used an O(N) space approach by tracking visited nodes in a hash set. Modify it to achieve O(1) space complexity.",
            "example": "Input: head = [3,2,0,-4], pos = 1\nOutput: true",
            "hint1": "Consider using two pointers.",
            "hint2": "Floyd's Tortoise and Hare algorithm: one pointer moves 1 step, the other moves 2 steps.",
            "code": "class Solution:\n    def hasCycle(self, head) -> bool:\n        seen = set()\n        current = head\n        while current:\n            if current in seen:\n                return True\n            seen.add(current)\n            current = current.next\n        return False",
            "fail_regex": "seen = set\\(\\)",
            "fail_msg": "Space complexity is O(N) due to hash set. Target is O(1).",
            "pass_regex": "slow|fast",
            "pass_msg": "Floyd's Tortoise and Hare implemented correctly! O(1) space."
        },
        {
            "title": "Valid Parentheses",
            "difficulty": "Easy",
            "timeLimit": "10m",
            "desc": "The LLM wrote a solution that fails when closing brackets appear before opening ones. Fix the logic.",
            "example": "Input: s = '(]'\nOutput: false",
            "hint1": "Use a stack data structure.",
            "hint2": "Push opening brackets. For closing brackets, pop and check for a match.",
            "code": "class Solution:\n    def isValid(self, s: str) -> bool:\n        count = 0\n        for char in s:\n            if char in '({[':\n                count += 1\n            elif char in ')}]':\n                count -= 1\n        return count == 0",
            "fail_regex": "count \\+= 1",
            "fail_msg": "Counting brackets doesn't ensure they are properly nested or of the right type. Use a stack.",
            "pass_regex": "append|pop",
            "pass_msg": "Excellent! A stack correctly validates the order and nesting of parentheses."
        },
        {
            "title": "Python Algorithmic Challenge 4",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        },
        {
            "title": "Python Algorithmic Challenge 5",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        },
        {
            "title": "Python Algorithmic Challenge 6",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        },
        {
            "title": "Python Algorithmic Challenge 7",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        },
        {
            "title": "Python Algorithmic Challenge 8",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        },
        {
            "title": "Python Algorithmic Challenge 9",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        },
        {
            "title": "Python Algorithmic Challenge 10",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM generated an inefficient solution. Review the code and optimize it for better performance.",
            "example": "Input: [1,2,3]\nOutput: [3,2,1]",
            "hint1": "Look for redundant operations.",
            "hint2": "Consider using built-in Python functions or a different data structure.",
            "code": "def solve(data):\n    # LLM generated inefficient code\n    result = []\n    for item in data:\n        result.insert(0, item)\n    return result",
            "fail_regex": "insert\\(0",
            "fail_msg": "Using insert(0, item) on a list is O(N), making the loop O(N^2). Use append and reverse, or slicing.",
            "pass_regex": "reverse|::-1",
            "pass_msg": "Good job! You optimized the list operation."
        }
    ],
    "cpp": [
        {
            "title": "Memory Leak in Tree Traversal",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM dynamically allocated memory for tree nodes but forgot to free them, causing a memory leak. Fix it.",
            "example": "Input: root = [1,2,3]\nOutput: (No memory leaks)",
            "hint1": "C++ requires manual memory management if you use 'new'.",
            "hint2": "Add a destructor or use smart pointers (std::unique_ptr).",
            "code": "class Tree {\npublic:\n    struct Node { int val; Node* left; Node* right; };\n    Node* root;\n    // LLM forgot to write a destructor\n};",
            "fail_regex": "// LLM forgot",
            "fail_msg": "You still have a memory leak. You need to implement ~Tree() and delete nodes.",
            "pass_regex": "~Tree|delete|unique_ptr",
            "pass_msg": "Memory leak fixed! Proper resource management is critical in C++."
        },
        {
            "title": "Pass by Value vs Reference",
            "difficulty": "Easy",
            "timeLimit": "10m",
            "desc": "The LLM is passing a massive vector by value into a recursive function, causing massive overhead. Optimize it.",
            "example": "Input: vector of 1M elements\nOutput: Fast execution",
            "hint1": "Passing by value copies the entire vector every time.",
            "hint2": "Pass by constant reference: const std::vector<int>&",
            "code": "void process(std::vector<int> data) {\n    // doing some read-only processing\n}",
            "fail_regex": "process\\(std::vector<int> data\\)",
            "fail_msg": "You are still passing by value. Add an ampersand (&) to pass by reference.",
            "pass_regex": "const std::vector<int>&|std::vector<int> &",
            "pass_msg": "Passed by reference! This prevents unnecessary copying."
        },
        {
            "title": "Out of Bounds Vector Access",
            "difficulty": "Easy",
            "timeLimit": "10m",
            "desc": "The LLM used the [] operator on a vector without bounds checking, which might segfault. Make it safer.",
            "example": "Input: index = 10, vector size = 5\nOutput: Handle error gracefully",
            "hint1": "Vector operator[] does not check bounds.",
            "hint2": "Use vector.at() instead, which throws std::out_of_range.",
            "code": "int getElement(std::vector<int>& v, int i) {\n    return v[i];\n}",
            "fail_regex": "v\\[i\\]",
            "fail_msg": "Still using the unsafe [] operator.",
            "pass_regex": "v\\.at\\(i\\)",
            "pass_msg": "Using .at() ensures an exception is thrown if the index is out of bounds."
        },
        {
            "title": "C++ System Design Challenge 4",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        },
        {
            "title": "C++ System Design Challenge 5",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        },
        {
            "title": "C++ System Design Challenge 6",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        },
        {
            "title": "C++ System Design Challenge 7",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        },
        {
            "title": "C++ System Design Challenge 8",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        },
        {
            "title": "C++ System Design Challenge 9",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        },
        {
            "title": "C++ System Design Challenge 10",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM wrote C++ code that is not thread-safe. Add a mutex lock to fix the race condition.",
            "example": "Input: Concurrent thread access\nOutput: No race conditions",
            "hint1": "Include <mutex>.",
            "hint2": "Use std::lock_guard.",
            "code": "int counter = 0;\nvoid increment() {\n    counter++; // Not thread safe\n}",
            "fail_regex": "counter\\+\\+; // Not thread safe",
            "fail_msg": "You need to lock the critical section.",
            "pass_regex": "std::lock_guard|mutex",
            "pass_msg": "Thread safety achieved using mutex locks!"
        }
    ],
    "rust": [
        {
            "title": "Borrow Checker Violation",
            "difficulty": "Medium",
            "timeLimit": "15m",
            "desc": "The LLM tried to mutate a string while holding an immutable reference to it. Fix the code to satisfy the borrow checker.",
            "example": "Input: s = String::from(\"hello\")\nOutput: \"hello world\"",
            "hint1": "You cannot have a mutable reference while an immutable one exists.",
            "hint2": "Drop the immutable reference or clone the string.",
            "code": "fn main() {\n    let mut s = String::from(\"hello\");\n    let r1 = &s;\n    s.push_str(\" world\");\n    println!(\"{}\", r1);\n}",
            "fail_regex": "let r1 = &s;",
            "fail_msg": "The borrow checker will still reject this. You cannot borrow 's' as mutable because it is also borrowed as immutable.",
            "pass_regex": "clone|//",
            "pass_msg": "Borrow checker satisfied! Welcome to Rust."
        },
        {
            "title": "Unsafe Block Misuse",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM used an 'unsafe' block to dereference a raw pointer unnecessarily. Refactor it to safe Rust.",
            "example": "Input: raw pointer\nOutput: Safe reference",
            "hint1": "Avoid raw pointers unless interacting with C code.",
            "hint2": "Use standard references &T or Box<T>.",
            "code": "fn main() {\n    let num = 5;\n    let r1 = &num as *const i32;\n    unsafe {\n        println!(\"r1 is: {}\", *r1);\n    }\n}",
            "fail_regex": "unsafe \\{",
            "fail_msg": "You are still using an unsafe block. Refactor to purely safe Rust.",
            "pass_regex": "&num",
            "pass_msg": "Good job! You removed the unsafe block and used safe references."
        },
        {
            "title": "Missing Error Handling",
            "difficulty": "Easy",
            "timeLimit": "10m",
            "desc": "The LLM used .unwrap() on a Result, which will panic if the file doesn't exist. Implement proper error handling.",
            "example": "Input: Missing file\nOutput: Graceful error message instead of panic",
            "hint1": "Don't use unwrap() in production code.",
            "hint2": "Use match or the ? operator.",
            "code": "use std::fs::File;\nfn main() {\n    let f = File::open(\"hello.txt\").unwrap();\n}",
            "fail_regex": "\\.unwrap\\(\\)",
            "fail_msg": ".unwrap() is still present. This will crash the program.",
            "pass_regex": "match|\\?",
            "pass_msg": "Excellent! Handling Results explicitly prevents unexpected panics."
        },
        {
            "title": "Rust Lifetimes Challenge 4",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        },
        {
            "title": "Rust Lifetimes Challenge 5",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        },
        {
            "title": "Rust Lifetimes Challenge 6",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        },
        {
            "title": "Rust Lifetimes Challenge 7",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        },
        {
            "title": "Rust Lifetimes Challenge 8",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        },
        {
            "title": "Rust Lifetimes Challenge 9",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        },
        {
            "title": "Rust Lifetimes Challenge 10",
            "difficulty": "Hard",
            "timeLimit": "20m",
            "desc": "The LLM failed to specify lifetimes for a function returning a reference. Add the correct lifetime annotations.",
            "example": "Input: Two strings\nOutput: The longer string",
            "hint1": "The compiler doesn't know which reference the returned reference points to.",
            "hint2": "Use <'a> to tie the input lifetimes to the output lifetime.",
            "code": "fn longest(x: &str, y: &str) -> &str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}",
            "fail_regex": "fn longest\\(x: &str, y: &str\\) -> &str",
            "fail_msg": "Missing lifetime annotations. Add <'a>.",
            "pass_regex": "<'a>",
            "pass_msg": "Lifetimes specified correctly! The Rust compiler is happy."
        }
    ]
};