const fs = require('fs');
let code = fs.readFileSync('apply.html', 'utf8');

const oldCardsRegex = /<div style="background:var\(--white\); border:2px solid var\(--primary-light\); padding:24px; border-radius:var\(--radius-lg\); box-shadow:var\(--shadow-sm\); flex:1 1 300px; min-width:280px; max-width:400px; display:flex; flex-direction:column; text-align:left;">/g;
const newCardsClass = '<div style="background:var(--white); border:2px solid var(--primary-light); padding:24px; border-radius:var(--radius-lg); box-shadow:var(--shadow-sm); flex:0 0 320px; scroll-snap-align:start; display:flex; flex-direction:column; text-align:left;">';
code = code.replace(oldCardsRegex, newCardsClass);

const btn1Regex = /<button type="button" onclick="saveRole\('\$\{m.roleName.replace\(\/'\/g, \\\\'\)\}', '\$\{m.domainFilter \|\| 'ALL'\}', '\$\{m.hourlyRate \|\| 'Market Rate'\}'\)" style="background:var\(--gray-100\); border:1px solid var\(--gray-200\); color:var\(--gray-700\); padding:0 14px; border-radius:var\(--radius-sm\); font-size:16px; cursor:pointer; transition:all 0.2s;" onmouseover="this.style.background='var\(--primary-light\)'; this.style.color='var\(--primary-dark\)';" onmouseout="this.style.background='var\(--gray-100\)'; this.style.color='var\(--gray-700\)';">💾<\/button>/g;
const btn1SVG = `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18"/><path d="M3 10h18"/><path d="M5 6l7-3 7 3"/><path d="M4 10v11"/><path d="M20 10v11"/><path d="M8 14v3"/><path d="M12 14v3"/><path d="M16 14v3"/></svg>`;

const btn2Regex = /<button type="button" onclick="markAsComplete\('\$\{m.roleName.replace\(\/'\/g, \\\\'\)\}', '\$\{m.domainFilter \|\| 'ALL'\}', '\$\{m.hourlyRate \|\| 'Market Rate'\}'\)" style="background:var\(--gray-100\); border:1px solid var\(--gray-200\); color:var\(--gray-700\); padding:0 14px; border-radius:var\(--radius-sm\); font-size:16px; cursor:pointer; transition:all 0.2s;" onmouseover="this.style.background='var\(--primary-light\)'; this.style.color='var\(--primary-dark\)';" onmouseout="this.style.background='var\(--gray-100\)'; this.style.color='var\(--gray-700\)';">✅<\/button>/g;
const btn2SVG = `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg>`;

const btn3Regex = /<button type="button" onclick="window.open\('resume-ats-guide\?role=' \+ encodeURIComponent\('\$\{m.roleName.replace\(\/'\/g, \\\\'\)\}'\), '_blank'\);" style="background:var\(--gray-100\); border:1px solid var\(--gray-200\); color:var\(--gray-700\); padding:0 14px; border-radius:var\(--radius-sm\); font-size:16px; cursor:pointer; transition:all 0.2s;" onmouseover="this.style.background='var\(--primary-light\)'; this.style.color='var\(--primary-dark\)';" onmouseout="this.style.background='var\(--gray-100\)'; this.style.color='var\(--gray-700\)';">🎯<\/button>/g;
const btn3SVG = `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>`;


code = code.replace(btn1Regex, `<button title="Save role to dashboard" type="button" onclick="saveRole('\${m.roleName.replace(/'/g, \\'\\'\\')}', '\${m.domainFilter || 'ALL'}', '\${m.hourlyRate || 'Market Rate'}')" style="background:var(--gray-100); border:1px solid var(--gray-200); color:var(--gray-700); padding:0 14px; border-radius:var(--radius-sm); font-size:16px; cursor:pointer; display:flex; align-items:center; justify-content:center; transition:all 0.2s;" onmouseover="this.style.background='var(--primary-light)'; this.style.color='var(--primary-dark)';" onmouseout="this.style.background='var(--gray-100)'; this.style.color='var(--gray-700)';">${btn1SVG}</button>`);
code = code.replace(btn2Regex, `<button title="Mark as Applied / Completed" type="button" onclick="markAsComplete('\${m.roleName.replace(/'/g, \\'\\'\\')}', '\${m.domainFilter || 'ALL'}', '\${m.hourlyRate || 'Market Rate'}')" style="background:var(--gray-100); border:1px solid var(--gray-200); color:var(--gray-700); padding:0 14px; border-radius:var(--radius-sm); font-size:16px; cursor:pointer; display:flex; align-items:center; justify-content:center; transition:all 0.2s;" onmouseover="this.style.background='var(--primary-light)'; this.style.color='var(--primary-dark)';" onmouseout="this.style.background='var(--gray-100)'; this.style.color='var(--gray-700)';">${btn2SVG}</button>`);
code = code.replace(btn3Regex, `<button title="Scan my resume to see if it matches this job" type="button" onclick="window.open('resume-ats-guide?role=' + encodeURIComponent('\${m.roleName.replace(/'/g, \\'\\'\\')}'), '_blank');" style="background:var(--gray-100); border:1px solid var(--gray-200); color:var(--gray-700); padding:0 14px; border-radius:var(--radius-sm); font-size:16px; cursor:pointer; display:flex; align-items:center; justify-content:center; transition:all 0.2s;" onmouseover="this.style.background='var(--primary-light)'; this.style.color='var(--primary-dark)';" onmouseout="this.style.background='var(--gray-100)'; this.style.color='var(--gray-700)';">${btn3SVG}</button>`);

// Fix regex escaping for title string literal that might have broken in node evaluation
fs.writeFileSync('apply.html', code);
console.log("Patched matched cards in apply.html");
